"""empty message

Revision ID: 11a00b9a6df6
Revises: 27ac36182330
Create Date: 2016-07-20 17:33:58.620285

"""

# revision identifiers, used by Alembic.
revision = '11a00b9a6df6'
down_revision = '27ac36182330'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('IDHash', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'student', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'family', ['family_id'], ['id'])
    op.add_column(u'user', sa.Column('family_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'family', ['family_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'family_id')
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column(u'student', 'family_id')
    op.drop_table('family')
    ### end Alembic commands ###
