"""empty message

Revision ID: 160db434d139
Revises: ebf8319209a7
Create Date: 2016-07-20 14:16:41.395112

"""

# revision identifiers, used by Alembic.
revision = '160db434d139'
down_revision = 'ebf8319209a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('DateTime', sa.DateTime(), nullable=True),
    sa.Column('Type', sa.String(length=24), nullable=True),
    sa.Column('MoveDetails', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_action')
    ### end Alembic commands ###
