"""empty message

Revision ID: 27ac36182330
Revises: 6c3ea6c06009
Create Date: 2016-07-20 17:24:05.699936

"""

# revision identifiers, used by Alembic.
revision = '27ac36182330'
down_revision = '6c3ea6c06009'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_credit', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_credit', 'session', ['session_id'], ['id'])
    op.drop_column('session_credit', 'rate')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_credit', sa.Column('rate', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session_credit', type_='foreignkey')
    op.drop_column('session_credit', 'session_id')
    ### end Alembic commands ###
