"""empty message

Revision ID: 69858d32aaff
Revises: 160db434d139
Create Date: 2016-07-20 16:08:00.219265

"""

# revision identifiers, used by Alembic.
revision = '69858d32aaff'
down_revision = '160db434d139'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_action', sa.Column('type', sa.String(length=24), nullable=True))
    op.drop_column('session_action', 'Type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_action', sa.Column('Type', sa.VARCHAR(length=24), autoincrement=False, nullable=True))
    op.drop_column('session_action', 'type')
    ### end Alembic commands ###
