"""empty message

Revision ID: 6c3ea6c06009
Revises: 69858d32aaff
Create Date: 2016-07-20 16:42:23.912660

"""

# revision identifiers, used by Alembic.
revision = '6c3ea6c06009'
down_revision = '69858d32aaff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('DateTime', sa.DateTime(), nullable=True),
    sa.Column('payer_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(length=120), nullable=True),
    sa.Column('isRefunded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('DateTime', sa.DateTime(), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_credit')
    op.drop_table('payment')
    ### end Alembic commands ###
