"""empty message

Revision ID: 72289a14b001
Revises: 232a0c5a78ff
Create Date: 2016-07-20 13:33:57.169495

"""

# revision identifiers, used by Alembic.
revision = '72289a14b001'
down_revision = '232a0c5a78ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'group', sa.Column('mentor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'group', 'mentor', ['mentor_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column(u'group', 'mentor_id')
    op.drop_table('student_rates')
    op.drop_table('mentor')
    ### end Alembic commands ###
