"""empty message

Revision ID: e70bd0375be8
Revises: 2b88b86a37a3
Create Date: 2016-07-19 16:42:29.025153

"""

# revision identifiers, used by Alembic.
revision = 'e70bd0375be8'
down_revision = '2b88b86a37a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'student', sa.Column('group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'group', ['group'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column(u'student', 'group')
    op.drop_table('group')
    ### end Alembic commands ###
